INSERT INTO xcart_states (state, code, country_code) VALUES ('Aberdeenshire','ABd','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Angus','AG','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Argyll','ARg','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Avon','AV','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Ayrshire','AY','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Banffshire','BF','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Bedfordshire','BE','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Berkshire','BK','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Buckinhamshire','BU','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Caithness','CN','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Cambridgeshire','CB','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Cheshire','CH','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Clackmannanshire','CL','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Cleveland','CV','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Clwyd','CW','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('County Antrim','CAn','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('County Armagh','CAr','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('County Down','CDo','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('County Durham','CDu','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('County Fermanagh','CFm','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('County Londonderry','CLd','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('County Tyrone','CTy','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Cornwall','COr','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Cumbria','CU','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Derbyshire','DB','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Devon','DV','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Dorset','DO','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Dumfriesshire','DF','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Dunbartonshire','DU','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Dyfed','DY','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('East Lothian','EL','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('East Sussex','ES','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Essex','EX','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Fife','FI','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Gloucestershire','GL','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Gwent','GW','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Gwynedd','GY','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Hampshire','HA','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Herefordshire','HE','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Hertfordshire','HF','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Inverness-shire','IS','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Arran','IsAr','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Barra','IsBa','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Benbecula','IsBe','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Bute','IsBu','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Canna','IsCa','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Coll','IsCo','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Colonsay','IsCl','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Cumbrae','IsCu','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Eigg','IsEg','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Gigha','IsGi','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Harris','IsHa','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Iona','IsIo','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Jura','IsJu','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Lewis','IsLw','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Mull','IsMu','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of North Uist','IsNu','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Buckinghamshire','BKM','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Huntingdonshire','HUN','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Kent','KEN','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Lancashire','LAN','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Leicestershire','LEI','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Lincolnshire','LIN','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Middlesex','MX','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Norfolk','NO','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Northamptonshire','NTH','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Northumberland','NU','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Nottinghamshire','NTT','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Oxfordshire','OX','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Rutland','RUT','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Shropshire','SR','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Somerset','SO','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Staffordshire','ST','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Suffolk','SF','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Surrey','SY','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Sussex','SU','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Warwickshire','WAR','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Westmorland','WES','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Wiltshire','WIt','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Worcestershire','WO','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Yorkshire','YKS','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Anglesey','AGY','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Carmarthenshire','CMN','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Cardiganshire','CGN','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Denbighshire','DEN','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Flintshire','FLN','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Glamorgan','GLA','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Monmouthshire','MON','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Montgomeryshire','MGY','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Pembrokeshire','PEM','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Radnorshire','RAD','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Berwickshire','BEW','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Kincardineshire','KCD','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Kinross-shire','KRS','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Kirkcudbrightshire','KKD','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Lanarkshire','LKS','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Midlothian','Mdl','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Morayshire','MOR','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Orkney','OKI','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Peebles-shire','PEE','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Perth','PER','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Renfrewshire','Rn','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Ross and Cromarty','ROC','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Roxburghshire','ROX','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Selkirkshire','SEL','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Shetland','SHI','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Stirlingshire','STI','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Sutherland','SUT','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('West Lothian','WLN','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Wigtownshire','WIG','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Rhum','IsRu','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Scalpay','IsSc','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Shetland','IsSh','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Skye','IsSk','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of South Uist','IsSu','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Tiree','IsTi','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isle of Wight','IsWi','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Isles of Scilly','IsScl','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('London','LO','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Merseyside','MER','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Mid Glamorgan','MG','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Nairnshire','NA','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('North Humberside','NHB','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('North Yorkshire','NYK','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Powys','PO','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('South Glamorgan','SG','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('South Humberside','SH','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('South Yorkshire','SYK','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('Tyne & Wear','TW','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('West Glamorgan','WG','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('West Midlands','WM','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('West Sussex','WS','GB');
INSERT INTO xcart_states (state, code, country_code) VALUES ('West Yorkshire','WYK','GB');

